server:
 port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka

turbine:
  app-config: MYCLOUD-PROVIDER-PRODUCT
  cluster-name-expression: new String("default")