spring:
 profiles:
   active:
    - dev2


---
server:
 port: 7002
eureka:
  server:
    eviction-interval-timer-in-ms: 60000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true #设置为false表示关闭保护模式
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false #不注册自己
    service-url:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka2  #,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka2 # 定义 Eureka 实例所在的主机名称

spring:
  profiles: dev1
  security:
    user:
      name: admin
      password: admin
      roles:
      - USER
      - ADMIN

---
server:
 port: 7002
eureka:
  server:
    eviction-interval-timer-in-ms: 60000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: true #设置为false表示关闭保护模式
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false #不注册自己
    service-url:
        #defaultZone: http://localhost:7001/eureka
        defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka  #,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka2 # 定义 Eureka 实例所在的主机名称

spring:
  profiles: dev2
  security:
    user:
      name: admin
      password: enjoy
      roles:
      - USER
      - ADMIN
